stages:
  - publish
publish:
  stage: publish
  image: docker:19.03.1
  services:
    - docker:19.03.1-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - apk add --repository https://alpine.secrethub.io/alpine/edge/main --allow-untrusted secrethub-cli
  script:
    - secrethub read company/app/docker/pasword | docker login -u $(secrethub read company/app/docker/username) --password-stdin
    - docker build -t company/app:${CI_COMMIT_SHA:0:7} .
    - docker push company/app:${CI_COMMIT_SHA:0:7}